name: GitHub Metrics - Achievements Compact

on:
  schedule:
    - cron: "0 0 * * *" # roda 1x por dia
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Usuário
          user: yerijhonrian

          # Base vazia (somente achievements)
          base: ""

          # Arquivo gerado
          filename: metrics.plugin.achievements.compact.svg

          # Plugin Achievements
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: X

          # Achievements específicos
          plugin_achievements_only: >-
            polyglot,
            stargazer,
            sponsor,
            deployer,
            member,
            maintainer,
            developer,
            scripter,
            packager,
            explorer,
            infographile,
            manager
