name: GitHub Metrics - Achievements Compact

on:
  schedule:
    - cron: "0 0 * * *" # roda 1x por dia
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Usuário
          user: yerijhonrian

          # Base vazia (somente achievements)
          base: ""

          # Arquivo gerado
          filename: metrics.achievements.svg

          # Plugin Achievements
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: X

          # Achievements específicos
          plugin_achievements_only: >-
            polyglot,
            stargazer,
            sponsor,
            deployer,
            member,
            maintainer,
            developer,
            scripter,
            packager,
            explorer,
            infographile,
            manager
      - name: Commit and push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add metrics.achievements.svg
          git commit -m "Update achievements metrics" || echo "No changes to commit"
          git push
