name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *" # atualiza todo dia
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: yerijhonrian
          template: dark
          base: ""

          filename: metrics.svg
          
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0
      - name: Commit and push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add metrics.svg
          git commit -m "Update metrics" || echo "No changes to commit"
          git push