name: GitHub Metrics - Achievements Safe

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GIT_HUB }}

          user: yerijhonrian
          base: ""
          filename: metrics.achievements.svg

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C

          # LISTA SEGURA (nÃ£o usa Projects)
          plugin_achievements_only: >-
            stargazer,
            developer,
            polyglot,
            scripter,
            explorer
